# To use:
#   $ conda env create -f env_cv.yml
#   $ conda activate cv
# Delete something
name: tf-plt
dependencies:
  - python=3.9
  - pip
  - pip:
    - ipykernel
    - numpy
    - tensorflow
    - matplotlib